services:
  - type: web
    name: troca-facil-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p app/static/uploads/perfil
      chmod 755 app/static/uploads/perfil
      alembic upgrade head
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
