"""add remaining tables

Revision ID: 036cd79bd1fa
Revises: 1f6a96909a1d
Create Date: 2026-01-29 13:32:58.860304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036cd79bd1fa'
down_revision: Union[str, Sequence[str], None] = '1f6a96909a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('exchangeoffer',
    sa.Column('id_offer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dada_datroca', sa.DateTime(), nullable=True),
    sa.Column('destricao', sa.String(length=500), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_offer')
    )
    op.create_table('review',
    sa.Column('id_review', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_avaliado', sa.Integer(), nullable=True),
    sa.Column('id_avaliador', sa.Integer(), nullable=True),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.String(length=500), nullable=True),
    sa.Column('data_avlicao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_avaliado'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_avaliador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_review')
    )
    op.create_table('servico',
    sa.Column('id_servico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('transfer',
    sa.Column('id_transfer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_exchangeoffer', sa.Integer(), nullable=True),
    sa.Column('data_datroca', sa.DateTime(), nullable=True),
    sa.Column('estados', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_exchangeoffer'], ['exchangeoffer.id_offer'], ),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_transfer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('servico')
    op.drop_table('review')
    op.drop_table('exchangeoffer')
    op.drop_table('category')
    # ### end Alembic commands ###
