"""add_data_criacao_to_servico

Revision ID: 098f975af2ce
Revises: fd1de3c01de3
Create Date: 2026-05-17 13:22:48.582676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098f975af2ce'
down_revision: Union[str, Sequence[str], None] = 'fd1de3c01de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'data_criacao')
    # ### end Alembic commands ###
