"""adicionar coluna mensagem

Revision ID: 12ca7a2e5a59
Revises: 38a7e4c8dd2a
Create Date: 2026-03-17 11:37:05.067526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ca7a2e5a59'
down_revision: Union[str, Sequence[str], None] = '38a7e4c8dd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangeoffer', sa.Column('mensagem', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'exchangeoffer', 'usuario', ['id_usuario_solicitante'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchangeoffer', type_='foreignkey')
    op.drop_column('exchangeoffer', 'mensagem')
    # ### end Alembic commands ###
