"""add_verification

Revision ID: 15f109b35f1d
Revises: 57ed1a8a4338
Create Date: 2026-04-20 23:17:53.301469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f109b35f1d'
down_revision: Union[str, Sequence[str], None] = '57ed1a8a4338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('codigo_verificacao', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'codigo_verificacao')
    op.drop_column('usuario', 'is_verified')
    # ### end Alembic commands ###
