"""ajuste user_sigle

Revision ID: 1f6a96909a1d
Revises: 
Create Date: 2026-01-29 13:00:36.791359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6a96909a1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('palavra_pass', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company',
    sa.Column('id_company', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nif_company', sa.Integer(), nullable=True),
    sa.Column('nome_empresa', sa.String(length=50), nullable=False),
    sa.Column('tipo_empresa', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_company'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_send', sa.Integer(), nullable=False),
    sa.Column('id_receiver', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=500), nullable=True),
    sa.Column('data_message', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_receiver'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_send'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_table('user_sigle',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_bi', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('numero_bi'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sigle')
    op.drop_table('message')
    op.drop_table('company')
    op.drop_table('usuario')
    # ### end Alembic commands ###
