"""adicionando coluna na tabela servico

Revision ID: 24215689da9c
Revises: 6bdc2dd708e1
Create Date: 2026-03-05 23:17:58.818372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24215689da9c'
down_revision: Union[str, Sequence[str], None] = '6bdc2dd708e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('nome', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'nome')
    # ### end Alembic commands ###
