"""adicionar a coluna mensagem e solicitante

Revision ID: 38a7e4c8dd2a
Revises: 24215689da9c
Create Date: 2026-03-10 14:51:42.218414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a7e4c8dd2a'
down_revision: Union[str, Sequence[str], None] = '24215689da9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('exchangeoffer', sa.Column('mensagem', sa.String(255), nullable=True))
    op.create_foreign_key(None, 'exchangeoffer', 'usuario', ['id_usuario_solicitante'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchangeoffer', type_='foreignkey')
    op.drop_column('exchangeoffer', 'mensagem')
    op.drop_column('exchangeoffer', 'id_usuario_solicitante')
    # ### end Alembic commands ###
