"""update exchange offer structure

Revision ID: 3b44418997ee
Revises: 81eca8a2baf2
Create Date: 2026-02-28 22:16:09.885179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b44418997ee'
down_revision: Union[str, Sequence[str], None] = '81eca8a2baf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangeoffer', sa.Column('id_servico_oferecido', sa.Integer(), nullable=False))
    op.add_column('exchangeoffer', sa.Column('id_servico_desejado', sa.Integer(), nullable=False))
    op.add_column('exchangeoffer', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('exchangeoffer', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.alter_column('exchangeoffer', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('exchangeoffer_ibfk_2'), 'exchangeoffer', type_='foreignkey')
    op.create_foreign_key(None, 'exchangeoffer', 'servico', ['id_servico_desejado'], ['id_servico'])
    op.create_foreign_key(None, 'exchangeoffer', 'servico', ['id_servico_oferecido'], ['id_servico'])
    op.drop_column('exchangeoffer', 'destricao')
    op.drop_column('exchangeoffer', 'id_servico')
    op.drop_column('exchangeoffer', 'dada_datroca')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangeoffer', sa.Column('dada_datroca', mysql.DATETIME(), nullable=True))
    op.add_column('exchangeoffer', sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exchangeoffer', sa.Column('destricao', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'exchangeoffer', type_='foreignkey')
    op.drop_constraint(None, 'exchangeoffer', type_='foreignkey')
    op.create_foreign_key(op.f('exchangeoffer_ibfk_2'), 'exchangeoffer', 'servico', ['id_servico'], ['id_servico'])
    op.alter_column('exchangeoffer', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('exchangeoffer', 'data_criacao')
    op.drop_column('exchangeoffer', 'status')
    op.drop_column('exchangeoffer', 'id_servico_desejado')
    op.drop_column('exchangeoffer', 'id_servico_oferecido')
    # ### end Alembic commands ###
