"""add status to servico

Revision ID: 4c31b6a94171
Revises: 764c76b6d3e7
Create Date: 2026-03-03 13:19:15.473713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c31b6a94171'
down_revision: Union[str, Sequence[str], None] = '764c76b6d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'status')
    # ### end Alembic commands ###
