"""adicionando viazualização na tabela mensagem

Revision ID: 57ed1a8a4338
Revises: acea203cbeb4
Create Date: 2026-03-21 23:46:46.158757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ed1a8a4338'
down_revision: Union[str, Sequence[str], None] = 'acea203cbeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('visualizacao', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'visualizacao')
    # ### end Alembic commands ###
