"""add_denuncia_table_and_is_dangerous_to_user

Revision ID: 681517a6c91f
Revises: 098f975af2ce
Create Date: 2026-05-17 13:29:03.296926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '681517a6c91f'
down_revision: Union[str, Sequence[str], None] = '098f975af2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('denuncias', ... ) -> Tabela já criada na tentativa anterior
    op.add_column('usuario', sa.Column('is_dangerous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_dangerous')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
