"""corrigir relacinamento do exchange e transfer

Revision ID: 6bdc2dd708e1
Revises: cc572ac0d82d
Create Date: 2026-03-05 21:18:24.044650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdc2dd708e1'
down_revision: Union[str, Sequence[str], None] = 'cc572ac0d82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
