"""recriar_tabela_service_booking

Revision ID: 73f93facc0e6
Revises: c4cdbcc1cbcf
Create Date: 2026-06-11 15:02:14.493690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73f93facc0e6'
down_revision: Union[str, Sequence[str], None] = 'c4cdbcc1cbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servico', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
