"""create payment_exchange table

Revision ID: 764c76b6d3e7
Revises: 3b44418997ee
Create Date: 2026-03-02 14:02:24.397793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764c76b6d3e7'
down_revision: Union[str, Sequence[str], None] = '3b44418997ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_exchanges',
    sa.Column('id_payment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_exchange_offer', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_exchange_offer'], ['exchangeoffer.id_offer'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_exchanges')
    # ### end Alembic commands ###
