"""add is_active and rating_media to usuario

Revision ID: 81ca78b362b0
Revises: e36016640c38
Create Date: 2026-05-13 16:18:01.985614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ca78b362b0'
down_revision: Union[str, Sequence[str], None] = 'e36016640c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('rating_media', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'rating_media')
    op.drop_column('usuario', 'is_active')
    # ### end Alembic commands ###
