"""add id_servico to exchangeoffer

Revision ID: 81eca8a2baf2
Revises: 036cd79bd1fa
Create Date: 2026-02-27 00:57:13.447745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81eca8a2baf2'
down_revision: Union[str, Sequence[str], None] = '036cd79bd1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangeoffer', sa.Column('id_servico', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exchangeoffer', 'servico', ['id_servico'], ['id_servico'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchangeoffer', type_='foreignkey')
    op.drop_column('exchangeoffer', 'id_servico')
    # ### end Alembic commands ###
