"""add_codigo_expiracao

Revision ID: 98c6448647f1
Revises: 15f109b35f1d
Create Date: 2026-04-23 17:20:48.692157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c6448647f1'
down_revision: Union[str, Sequence[str], None] = '15f109b35f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('codigo_expiracao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'codigo_expiracao')
    # ### end Alembic commands ###
