"""adicionando coluna na tabela exchange

Revision ID: acea203cbeb4
Revises: 12ca7a2e5a59
Create Date: 2026-03-17 12:28:18.377452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acea203cbeb4'
down_revision: Union[str, Sequence[str], None] = '12ca7a2e5a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangeoffer', sa.Column('data_resposta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchangeoffer', 'data_resposta')
    # ### end Alembic commands ###
