"""adicionar o relacionamento do review com exchange

Revision ID: cc572ac0d82d
Revises: 4c31b6a94171
Create Date: 2026-03-04 00:11:49.537844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc572ac0d82d'
down_revision: Union[str, Sequence[str], None] = '4c31b6a94171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('id_exchange_offer', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('data_avaliacao', sa.DateTime(), nullable=True))
    op.alter_column('review', 'id_avaliado',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('review', 'id_avaliador',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('review', 'avaliacao',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'review', 'exchangeoffer', ['id_exchange_offer'], ['id_offer'])
    op.drop_column('review', 'data_avlicao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('data_avlicao', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.alter_column('review', 'avaliacao',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('review', 'id_avaliador',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('review', 'id_avaliado',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('review', 'data_avaliacao')
    op.drop_column('review', 'id_exchange_offer')
    # ### end Alembic commands ###
