"""add foto_perfil to usuario

Revision ID: e36016640c38
Revises: 98c6448647f1
Create Date: 2026-05-13 15:51:41.155909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e36016640c38'
down_revision: Union[str, Sequence[str], None] = '98c6448647f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['nif_company'])
    op.alter_column('user_sigle', 'numero_bi',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.add_column('usuario', sa.Column('foto_perfil', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto_perfil')
    op.alter_column('user_sigle', 'numero_bi',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
