"""add_stripe_fields_to_payment_exchange

Revision ID: efcf6d765f5a
Revises: 81ca78b362b0
Create Date: 2026-05-17 11:17:55.142160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcf6d765f5a'
down_revision: Union[str, Sequence[str], None] = '81ca78b362b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_exchanges', sa.Column('id_user', sa.Integer(), nullable=True))
    op.add_column('payment_exchanges', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payment_exchanges', ['stripe_payment_intent_id'])
    op.create_foreign_key(None, 'payment_exchanges', 'usuario', ['id_user'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_exchanges', type_='foreignkey')
    op.drop_constraint(None, 'payment_exchanges', type_='unique')
    op.drop_column('payment_exchanges', 'stripe_payment_intent_id')
    op.drop_column('payment_exchanges', 'id_user')
    # ### end Alembic commands ###
