"""make_transfer_columns_non_nullable_and_fix_exchangeoffer_mensagem

Revision ID: f3e98805bfa4
Revises: c4cdbcc1cbcf
Create Date: 2026-06-18 21:09:13.988039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3e98805bfa4'
down_revision: Union[str, Sequence[str], None] = 'c4cdbcc1cbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
# op.drop_table('service_booking')  # table does not exist
    op.alter_column('servico', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('transfer', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'id_usuario_solicitante',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'id_exchangeoffer',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'data_datroca',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('transfer', 'estados',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'estados',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transfer', 'data_datroca',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('transfer', 'id_exchangeoffer',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'id_usuario_solicitante',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('servico', 'data_criacao',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_table('service_booking',
    sa.Column('id_pedido', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_prestador', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_agendada', mysql.DATETIME(), nullable=False),
    sa.Column('mensagem', mysql.TEXT(), nullable=True),
    sa.Column('preco_acordado', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('service_booking_ibfk_2')),
    sa.ForeignKeyConstraint(['id_prestador'], ['usuario.id_usuario'], name=op.f('service_booking_ibfk_3')),
    sa.ForeignKeyConstraint(['id_servico'], ['servico.id_servico'], name=op.f('service_booking_ibfk_1')),
    sa.PrimaryKeyConstraint('id_pedido'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
