"""add_freemium_fields_to_user

Revision ID: fd1de3c01de3
Revises: efcf6d765f5a
Create Date: 2026-05-17 13:11:26.299463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1de3c01de3'
down_revision: Union[str, Sequence[str], None] = 'efcf6d765f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('plano', sa.String(length=10), nullable=False))
    op.add_column('usuario', sa.Column('premium_ate', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'stripe_subscription_id')
    op.drop_column('usuario', 'stripe_customer_id')
    op.drop_column('usuario', 'premium_ate')
    op.drop_column('usuario', 'plano')
    # ### end Alembic commands ###
